WAIT_UNIT: 1
OBJECT_WAIT_TIME: 150
OBJECT_WAIT_TIME1: 10
PAGELOAD_WAIT_TIME: 150
SCRIPT_WAIT_TIME: 45
ALERT_WAIT_TIME: 8
FLUENT_WAIT_FLAG: Y
FLUENT_WAIT_POLLING_SECONDS: 2
WAIT_TIME1: 3
WAIT_TIME2: 6
WAIT_TIME3: 10
WAIT_TIME4: 15
WAIT_TIME5: 25
WAIT_TIME6: 60
WAIT_FOR_SECOND: 1
MS_OFFICE_VERSION: 2013
OPERATING_SYSTEM: Win7
ENVIRONMENT: EVO
STATIC_NAME: "NULL"